import { SAHAY_SMS_NUMBER } from "./contact";
import type { LangCode } from "./types";

export function buildChecklistText(schemeName: string, docs: string[], lang: LangCode): string {
  const headers: Record<LangCode, string> = {
    en: `Sahay document checklist — ${schemeName}`,
    hi: `सहाय दस्तावेज़ सूची — ${schemeName}`,
    ta: `Sahay ஆவண பட்டியல் — ${schemeName}`,
    mr: `सहाय कागदपत्र यादी — ${schemeName}`,
    bn: `সহায় নথি তালিকা — ${schemeName}`,
    te: `సహాయ్ పత్రాల జాబితా — ${schemeName}`,
  };
  const lines = docs.map((d, i) => `${i + 1}. [ ] ${d}`);
  return `${headers[lang]}\n\n${lines.join("\n")}\n\nSource: MyScheme.gov.in\n— Sahay`;
}

export function downloadChecklistPdf(schemeName: string, docs: string[], lang: LangCode): void {
  const text = buildChecklistText(schemeName, docs, lang);
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${schemeName} Checklist</title>
<style>body{font-family:system-ui;padding:40px;max-width:600px}h1{font-size:20px}li{margin:8px 0;font-size:14px}.meta{color:#666;font-size:12px;margin-top:24px}</style></head>
<body><h1>${schemeName}</h1><ul>${docs.map((d) => `<li>${d}</li>`).join("")}</ul>
<p class="meta">Source: MyScheme.gov.in — Generated by Sahay</p></body></html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${schemeName.replace(/\s+/g, "-").toLowerCase()}-checklist.html`;
  a.click();
  URL.revokeObjectURL(url);

  // Also offer plain text fallback
  void text;
}

export function sendChecklistSms(schemeName: string, docs: string[], lang: LangCode, phone = SAHAY_SMS_NUMBER): void {
  const body = buildChecklistText(schemeName, docs.slice(0, 5), lang);
  const uri = `sms:${phone}?body=${encodeURIComponent(body.slice(0, 900))}`;
  window.location.href = uri;
}

export function shareWhatsApp(text: string): void {
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer");
}

export function shareScheme(schemeName: string, desc: string, source: string): void {
  shareWhatsApp(`Sahay matched me to ${schemeName}: ${desc}\n${source}`);
}
